version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ".:/src"
      - "./secrets:/run/secrets"
    entrypoint: ["/src/docker/entrypoint-dev.sh"]
